### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tuchang** [0xHJK/music-dl#15]
**问题描述**
搜索的结果里面没有网易音乐源的音乐

- 搜索的关键字：
- 出错的音乐源：NetEase
- 使用的命令：`-s netease`

**使用的环境**
- 操作系统版本：
- Python版本：

**截图**
使用`-v`参数运行，截取完整错误信息
`[2019-02-17 20:28:34] ERROR    | music_dl.__main__: Get NETEASE music list failed. 
[2019-02-17 20:28:34] ERROR    | music_dl.__main__: No module named 'Crypto' `

`[2019-02-17 20:32:41] ERROR    | music_dl.__main__: Get NETEASE music list failed. 
[2019-02-17 20:32:41] ERROR    | music_dl.__main__: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/music_dl/core.py", line 25, in music_search
    addon = importlib.import_module('.extractors.' + source, __package__)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/music_dl/extractors/netease.py", line 15, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'`

**修改建议**

**Comment by 0xHJK** [comment]
依赖库没安装好，先运行`pip3 install -r requirements.txt`

**Comment by tuchang** [comment]
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
@0xHJK

**Comment by 0xHJK** [comment]
你用的是最新的代码吗？`requirements.txt`不是就在项目里面吗？
或者你直接用pip安装吧，`pip3 install pymusic-dl`这样最方便了

**Comment by tuchang** [comment]
我就是用的`pip3 install pymusic-dl`啊 没有用别的方法装

**Comment by 0xHJK** [comment]
说一下安装的版本，操作系统版本和python版本

**Comment by tuchang** [comment]
2.0.1
macos 10.14
python 3.7.0

**Comment by tuchang** [comment]
什么也没改 最近不能复现这个问题了 中间没有更新过music-dl、系统或python

**Comment by 0xHJK** [comment]
报错是因为你没有安装用来加密的那个库。
可能你系统里装了多个版本的python，比如用了pyenv或者conda之类的，然后切换了python环境。也可能不小心删除了这个库，后来安装别的包的时候又把这个库装上了。
