### ISSUE TITLE
[BUG] --version选项错误

### ISSUE THREAD

**Issue by chenxiex** [0xHJK/music-dl#78]
**问题描述（Question description）**
music-dl --version
命令报错：
`Traceback (most recent call last):
  File "/home/username/.local/bin/music-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/lib/python3/dist-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 380, in callback
    raise RuntimeError(
RuntimeError: 'music_dl' is not installed. Try passing 'package_name' instead.`

**使用的环境（Environment）**
- 安装方式（Installation method）：pip
- music-dl版本（music-dl version）：
- 操作系统版本（OS version）：ubuntu 22.04
- Python版本（Python version）：Python 3.10.6

**Comment by flyzyh** [comment]
俺也一样
具体来说是啥命令都报错
MacOS15，python3.13

<img width="2384" height="974" alt="Image" src="https://github.com/user-attachments/assets/f1463118-9e43-4ece-a447-51b58973bce4" />
